# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HubCall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HubCall
  pod 'MSAL'
  pod 'MSGraphClientSDK' #, ' ~> 1.0.0'
  pod 'MSGraphClientModels' #, '~> 1.3.0'

end
